server:
  port: '8089'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
          nodeValue: TRACE

spring:
  application:
    name: api-gateway
## basic module route
  cloud:
    gateway:
      routes:
        - id: basic_route
          uri: lb://basic
          predicates:
            - Path=/trainee/**,/trainer/**,/training/**,/training-type/**,/user/**,/login
## workload module route
        - id: workload_route
          uri: lb://workload
          predicates:
            - Path=/workload/**